name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
        PORT: 5000
        WEB_APP_ORIGIN: 'http://localhost:8080'
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        USE_UNSECURE_COOKIE: 'true'
        SESSION_ID_NAME: 'candlsid'
        USE_CSRF_TOKEN: 'false'
        COOKIE_DOMAIN: 'localhost'
        USE_SESSION_PROXY: 'true'
